/*
 * JSP generated by Resin-4.0.36 (built Fri, 26 Apr 2013 03:31:59 PDT)
 */

package _jsp._WEB_22dINF._views;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.List;
import com.channelsoft.ems.po.MessagePo;

public class _userMessage__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    List list1=(List)request.getAttribute("list1");
					MessagePo po=(MessagePo)list1.get(0);

				
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((po.getfPhotoID()));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((po.getfStaffName()));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((po.getfSex()));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((po.getfStaffStatus()));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((po.getfFnation()));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((po.getfDepartmentName()));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((po.getfPost()));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((po.getfTitle()));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((po.getfSalryType()));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((po.getfIdentityCardID()));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((po.getfBrith()));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((po.getfMaritalStatus()));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((po.getfHealth()));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((po.getfPoliticalStatus()));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((po.getfEntryDate()));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((po.getfDismissalDate()));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((po.getfHpisejpldRegister()));
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((po.getfGraduateSchool()));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.print((po.getfEducation()));
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((po.getfMajor()));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((po.getfComputerLevel()));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((po.getfCertificate()));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((po.getfLanguageLevel()));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((po.getfBuildingName()));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((po.getfMobileTel()));
    out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print((po.getfBankCardID()));
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((po.getfTel()));
    out.write(_jsp_string34, 0, _jsp_string34.length);
    out.print((po.getfPostcode()));
    out.write(_jsp_string35, 0, _jsp_string35.length);
    out.print((po.getfWechatNumber()));
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((po.getfHomeAddress()));
    out.write(_jsp_string37, 0, _jsp_string37.length);
    out.print((po.getfRemarks()));
    out.write(_jsp_string38, 0, _jsp_string38.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string39, 0, _jsp_string39.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string40, 0, _jsp_string40.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string41, 0, _jsp_string41.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string42, 0, _jsp_string42.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string43, 0, _jsp_string43.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string44, 0, _jsp_string44.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string45, 0, _jsp_string45.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string46, 0, _jsp_string46.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string47, 0, _jsp_string47.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1842010395327194821L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/views/userMessage.jsp"), -2128686247175277754L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${pageContext.request.contextPath}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;

  private final static char []_jsp_string27;
  private final static char []_jsp_string40;
  private final static char []_jsp_string6;
  private final static char []_jsp_string11;
  private final static char []_jsp_string16;
  private final static char []_jsp_string23;
  private final static char []_jsp_string47;
  private final static char []_jsp_string10;
  private final static char []_jsp_string13;
  private final static char []_jsp_string14;
  private final static char []_jsp_string25;
  private final static char []_jsp_string18;
  private final static char []_jsp_string30;
  private final static char []_jsp_string35;
  private final static char []_jsp_string32;
  private final static char []_jsp_string0;
  private final static char []_jsp_string41;
  private final static char []_jsp_string31;
  private final static char []_jsp_string36;
  private final static char []_jsp_string44;
  private final static char []_jsp_string7;
  private final static char []_jsp_string15;
  private final static char []_jsp_string34;
  private final static char []_jsp_string46;
  private final static char []_jsp_string20;
  private final static char []_jsp_string1;
  private final static char []_jsp_string9;
  private final static char []_jsp_string29;
  private final static char []_jsp_string33;
  private final static char []_jsp_string12;
  private final static char []_jsp_string37;
  private final static char []_jsp_string24;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  private final static char []_jsp_string39;
  private final static char []_jsp_string19;
  private final static char []_jsp_string45;
  private final static char []_jsp_string3;
  private final static char []_jsp_string22;
  private final static char []_jsp_string26;
  private final static char []_jsp_string8;
  private final static char []_jsp_string28;
  private final static char []_jsp_string42;
  private final static char []_jsp_string17;
  private final static char []_jsp_string43;
  private final static char []_jsp_string2;
  private final static char []_jsp_string21;
  private final static char []_jsp_string38;
  static {
    _jsp_string27 = "\" type=\"text\" maxlength=\"40\" id=\"updateMajor\" readonly=\"readonly\"  style=\"width: 90px;height: 23px\">\r\n\r\n\r\n					</td>\r\n					<td align=\"right\">\u7535\u8111\u6c34\u5e73\uff1a</td>\r\n					<td>\r\n						<input name=\"computer\" value=\"".toCharArray();
    _jsp_string40 = "/script/lib/H+/js/bootstrap.min.js?v=3.3.6\"></script>\r\n\r\n    <!-- \u81ea\u5b9a\u4e49js -->\r\n    <script src=\"".toCharArray();
    _jsp_string6 = "\r\n				<tr>\r\n					<td></td>\r\n					<td></td>\r\n					<td>&nbsp;</td>\r\n					<td>&nbsp;</td>\r\n					<td></td>\r\n					<td></td>\r\n					<td></td>\r\n					<td></td>\r\n					<td rowspan=\"8\" style=\"text-align: center;vertical-align: middle;\">\r\n\r\n						<img id=\"Imagel1\" src=\"".toCharArray();
    _jsp_string11 = "\" id=\"updateStature\"   readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u6c11\u65cf\uff1a</td>\r\n					<td>\r\n						<input name=\"nation\" value=\"".toCharArray();
    _jsp_string16 = "\" id=\"updateSal\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u8eab\u4efd\u8bc1\u53f7\uff1a</td>\r\n					<td>\r\n						<input name=\"idCard\" value=\"".toCharArray();
    _jsp_string23 = "\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u6237\u7c4d\uff1a</td>\r\n					<td>\r\n						<input name=\"census\" value=\" ".toCharArray();
    _jsp_string47 = "\";\r\n\r\n	</script>\r\n\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string10 = "\" id=\"updateSex\" class=\"input_text\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n\r\n					</td>\r\n					<td align=\"right\">&nbsp;\u72b6\u6001\uff1a</td>\r\n					<td>\r\n						<input  name=\"dropStature\" value=\"".toCharArray();
    _jsp_string13 = "\" id=\"updateDepartment\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u804c\u52a1\uff1a</td>\r\n					<td>\r\n						<input name=\"duty\" value=\"".toCharArray();
    _jsp_string14 = "\"  id=\"updateDuty\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u804c\u79f0\uff1a</td>\r\n					<td>\r\n						<input name=\"jobTitle\" value=\"".toCharArray();
    _jsp_string25 = "\"  type=\"text\" maxlength=\"40\" id=\"updateGraduateSchool\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n					</td>\r\n					<td align=\"right\">\u5b66\u5386\uff1a</td>\r\n					<td>\r\n						<input name=\"education\" value=\"  ".toCharArray();
    _jsp_string18 = "\"  id=\"updateBirth\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u5a5a\u59fb\u72b6\u51b5</td>\r\n					<td>\r\n						<input name=\"marry\"  value=\"".toCharArray();
    _jsp_string30 = "\" id=\"updateLanguageLevel\" readonly=\"readonly\"  style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u6240\u5c5e\u5927\u53a6\uff1a</td>\r\n					<td>\r\n						<input  name=\"FBuildingID\" value=\"".toCharArray();
    _jsp_string35 = "\" type=\"text\" maxlength=\"11\" id=\"updatePostcode\"  readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n						</td>\r\n					<td align=\"right\">\u5fae\u4fe1\u53f7\uff1a</td>\r\n					<td>\r\n						<input name=\"FWechatNumber\" value=\" ".toCharArray();
    _jsp_string32 = "\" type=\"text\" maxlength=\"11\" id=\"updateMobileTel\"  readonly=\"readonly\"  style=\"width: 90px;height: 23px\">\r\n\r\n						</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u94f6\u884c\u5361\u53f7\uff1a</td>\r\n					<td>\r\n						<input  name=\"cardId\" value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n	<head>\r\n	    <meta charset=\"utf-8\">\r\n	    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n\r\n		<title>\u4e2a\u4eba\u8d44\u6599</title>\r\n	\r\n	    <link rel=\"shortcut icon\" href=\"favicon.ico\"> \r\n	    <link href=\"".toCharArray();
    _jsp_string41 = "/script/lib/H+/js/content.js?v=1.0.0\"></script>\r\n	<script src=\"".toCharArray();
    _jsp_string31 = "\" id=\"updateBuildingID\" readonly=\"readonly\"  style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u624b\u673a\uff1a</td>\r\n					<td>\r\n						<input  name=\"FMobileTel\" value=\"".toCharArray();
    _jsp_string36 = "\"  type=\"text\" maxlength=\"11\" id=\"updateWechatNumber\"  readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u901a\u8baf\u5730\u5740\uff1a</td>\r\n					<td colspan=\"8\">\r\n						<input name=\"Phone\" value=\"".toCharArray();
    _jsp_string44 = "/script/lib/H+/js/plugins/bootstrap-table/bootstrap-table.min.js\"></script>\r\n    <script src=\"".toCharArray();
    _jsp_string7 = "\\\\img\\\\".toCharArray();
    _jsp_string15 = "\"  id=\"updateTitle\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u85aa\u8d44\u7c7b\u522b\uff1a</td>\r\n					<td>\r\n						<input name=\"sal\" value=\"".toCharArray();
    _jsp_string34 = "\" type=\"text\" maxlength=\"11\" id=\"updateTel\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u90ae\u653f\u7f16\u53f7\uff1a</td>\r\n					<td>\r\n						<input name=\"FPostcode\" value=\"".toCharArray();
    _jsp_string46 = "/script/lib/H+/js/plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js\"></script>\r\n	<script type=\"text/javascript\">\r\n			var contextPath = \"".toCharArray();
    _jsp_string20 = "\"  type=\"text\" maxlength=\"20\" id=\"updateHealth\"  readonly=\"readonly\"  style=\"width: 90px;height: 23px\">\r\n\r\n						</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u653f\u6cbb\u9762\u8c8c\uff1a</td>\r\n					<td>\r\n						<input name=\"political\"value=\"".toCharArray();
    _jsp_string1 = "/script/lib/H+/css/bootstrap.min.css?v=3.3.6\" rel=\"stylesheet\">\r\n	    <link href=\"".toCharArray();
    _jsp_string9 = "\" type=\"text\" maxlength=\"3\" id=\"updatetxtName\" readonly=\"readonly\" required style=\"width: 90px;height: 23px\">\r\n					</td>\r\n					<td align=\"right\">\u6027\u522b\uff1a</td>\r\n					<td>\r\n						<input name=\"dropSex\" value=\"".toCharArray();
    _jsp_string29 = "\" type=\"text\" maxlength=\"200\" id=\"updateCertificate\"  readonly=\"readonly\"  style=\"width: 90px;height: 23px\">\r\n					</td>\r\n					<td align=\"right\">\u5916\u8bed\u6c34\u5e73\uff1a</td>\r\n					<td>\r\n						<input name=\"foreign\" value=\" ".toCharArray();
    _jsp_string33 = "\" type=\"text\" maxlength=\"19\" id=\"updateBankCard\"   readonly=\"readonly\" style=\"width: 205px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u56fa\u5b9a\u7535\u8bdd\uff1a</td>\r\n					<td>\r\n						<input name=\"FTel\" value=\"".toCharArray();
    _jsp_string12 = "\"   id=\"updateNation\" class=\"input_text\"  readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u90e8\u95e8\uff1a</td>\r\n					<td>\r\n						<input  name=\"emp\" value=\"".toCharArray();
    _jsp_string37 = "\" type=\"text\" maxlength=\"200\" id=\"updateMalingAddress\"  readonly=\"readonly\" style=\"width: 710px;height: 23px\">\r\n\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u5907\u6ce8\uff1a</td>\r\n					<td colspan=\"8\">\r\n						<input name=\"remark\" value=\" ".toCharArray();
    _jsp_string24 = "\" type=\"text\" maxlength=\"40\" id=\"updateCensus\"  readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u6bd5\u4e1a\u9662\u6821\uff1a</td>\r\n					<td>\r\n						<input name=\"school\" value=\"".toCharArray();
    _jsp_string4 = "/script/lib/H+/css/animate.css\" rel=\"stylesheet\">\r\n	    <link href=\"".toCharArray();
    _jsp_string5 = "/script/lib/H+/css/style.css?v=4.1.0\" rel=\"stylesheet\">\r\n	</head>\r\n\r\n<body class=\"gray-bg\">\r\n<div class=\"modal-content\">\r\n	<div class=\"modal-header\">\r\n		<h4 class=\"modal-title\" id=\"myModalLabel\">\u7528\u6237\u8d44\u6599</h4>\r\n	</div>\r\n	<div class=\"modal-body\" style=\"height: 550px;\">\r\n		<div class=\"popover-content\" style=\"width: 1000px;\">\r\n			<table style=\"width: 950px;position: relative; top: -30px;\">\r\n				<tbody>\r\n				".toCharArray();
    _jsp_string39 = "/script/lib/H+/js/jquery.min.js?v=2.1.4\"></script>\r\n    <script src=\"".toCharArray();
    _jsp_string19 = "\" id=\"updateMaritalStatus\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n						</td>\r\n					<td align=\"right\">\u5065\u5eb7\u72b6\u51b5</td>\r\n					<td>\r\n						<input name=\"health\" value=\"".toCharArray();
    _jsp_string45 = "/script/lib/H+/js/plugins/bootstrap-table/bootstrap-table-mobile.min.js\"></script>\r\n    <script src=\"".toCharArray();
    _jsp_string3 = "/script/lib/H+/css/plugins/bootstrap-table/bootstrap-table.min.css\" rel=\"stylesheet\">\r\n	    <link href=\"".toCharArray();
    _jsp_string22 = "\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n\r\n					<td align=\"right\">\u89e3\u8058\u65e5\u671f\uff1a</td>\r\n					<td>\r\n						<input  type=\"text\" id=\"updateDismissalDate\"  value=\"".toCharArray();
    _jsp_string26 = "\" id=\"updateEducation\"  readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u4e13\u4e1a\uff1a</td>\r\n					<td>\r\n						<input name=\"major\" value=\"".toCharArray();
    _jsp_string8 = "\" style=\"height: 135px;width: 110px;\">\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u59d3\u540d\uff1a</td>\r\n					<td>\r\n						<input name=\"textName\" value=\"".toCharArray();
    _jsp_string28 = "\" id=\"updateComputer\" readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n				</tr>\r\n				<tr>\r\n					<td align=\"right\">\u6240\u6301\u8bc1\u4e66\uff1a</td>\r\n					<td>\r\n						<input name=\"usbKey\" value=\"".toCharArray();
    _jsp_string42 = "/script/app-resources/rate-range/rateRange.js\"></script>\r\n	<script src=\"".toCharArray();
    _jsp_string17 = "\" id=\"updateIdentityCardID\" type=\"text\" maxlength=\"18\" readonly=\"readonly\"   style=\"width: 205px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u51fa\u751f\u65e5\u671f\uff1a</td>\r\n					<td>\r\n						<input   type=\"text\" value=\"".toCharArray();
    _jsp_string43 = "/script/app-resources/common/alert.js\"></script>\r\n	\r\n    <!-- Bootstrap table -->\r\n    <script src=\"".toCharArray();
    _jsp_string2 = "/script/lib/H+/css/font-awesome.css?v=4.4.0\" rel=\"stylesheet\">\r\n	    <link href=\"".toCharArray();
    _jsp_string21 = "\" type=\"text\" maxlength=\"20\" id=\"updatePoliticalStatus\"  readonly=\"readonly\" style=\"width: 90px;height: 23px\">\r\n\r\n					</td>\r\n					<td align=\"right\">\u5165\u804c\u65e5\u671f\uff1a</td>\r\n					<td>\r\n						<input   type=\"text\" id=\"updateEntryDate\"  value=\" ".toCharArray();
    _jsp_string38 = "\" type=\"text\" maxlength=\"200\" id=\"updateRemark\"  readonly=\"readonly\" style=\"width: 710px;height: 23px\">\r\n\r\n					</td>\r\n				</tr>\r\n				</tbody>\r\n			</table>\r\n		</div>\r\n	</div>\r\n</div>\r\n\r\n\r\n\r\n    <!-- \u5168\u5c40js -->\r\n    <script src=\"".toCharArray();
  }
}
